import { execFile } from "node:child_process";
import { constants } from "node:fs";
import { lstat, mkdir, open, realpath, rename, rm } from "node:fs/promises";
import { dirname, isAbsolute, join, parse, relative, resolve } from "node:path";
import type { Config, JevCredentialSource } from "./config.js";

export const JEV_KEYRING_REFERENCE = "pi-guardrails/jev";
const MAX_BYTES = 64 * 1024;
export class JevCredentialError extends Error {}
const validKey = (v: unknown): v is string => typeof v === "string" && v.length > 0 && v.length <= 16384 && !/[\s\x00-\x1f\x7f-\x9f]/.test(v);
export function defaultJevCredentialPath(agentDir: string): string { return join(agentDir, "guardrails", "jev.credentials.json"); }
export function validJevReference(source: JevCredentialSource, value: string): boolean {
  return source === "environment" ? /^[A-Za-z_][A-Za-z0-9_]{0,255}$/.test(value) : source === "keyring" ? value === JEV_KEYRING_REFERENCE : value.length > 0 && value.length <= 4096 && isAbsolute(value);
}
async function existingAncestor(path: string): Promise<string> { let current = resolve(path); for (;;) { try { await lstat(current); return current; } catch (e) { if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw new JevCredentialError("Unsafe credential path"); const parent = dirname(current); if (parent === current) throw new JevCredentialError("Unsafe credential path"); current = parent; } } }
async function safePath(path: string, create: boolean): Promise<void> {
  const absolute = resolve(path); const ancestor = await existingAncestor(create ? dirname(absolute) : absolute); const physical = await realpath(ancestor).catch(() => { throw new JevCredentialError("Unsafe credential path"); });
  for (let cursor = physical;; cursor = dirname(cursor)) { try { const git = await lstat(join(cursor, ".git")); if (git.isDirectory() || git.isFile()) throw new JevCredentialError("Credential files must be outside repositories"); } catch (e) { if (e instanceof JevCredentialError) throw e; if (!['ENOENT','ENOTDIR'].includes((e as NodeJS.ErrnoException).code ?? '')) throw new JevCredentialError("Unsafe credential path"); } const parent = dirname(cursor); if (parent === cursor) break; }
  const root = parse(absolute).root; let cursor = root;
  for (const part of relative(root, create ? dirname(absolute) : absolute).split(/[\\/]/).filter(Boolean)) { cursor = join(cursor, part); try { const stat = await lstat(cursor); if (stat.isSymbolicLink()) throw new JevCredentialError("Unsafe credential path"); if (cursor !== absolute && !stat.isDirectory()) throw new JevCredentialError("Unsafe credential path"); if (stat.isDirectory() && cursor === dirname(absolute) && process.platform !== "win32" && (stat.uid !== process.getuid?.() || (stat.mode & 0o077) !== 0)) throw new JevCredentialError("Credential directory must be owner-only"); } catch (e) { if (e instanceof JevCredentialError) throw e; if ((e as NodeJS.ErrnoException).code === "ENOENT" && create) break; throw new JevCredentialError("Unsafe credential path"); } }
}
async function readFileKey(path: string): Promise<string> { await safePath(path, false); const before = await lstat(path); if (!before.isFile() || before.isSymbolicLink()) throw new JevCredentialError("Unsafe credential file"); const file = await open(path, constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK); try { const stat = await file.stat(); if (!stat.isFile() || stat.ino !== before.ino || stat.dev !== before.dev || stat.size > MAX_BYTES || process.platform !== "win32" && (stat.uid !== process.getuid?.() || (stat.mode & 0o777) !== 0o600)) throw new JevCredentialError("Unsafe credential file"); const buffer = Buffer.alloc(MAX_BYTES + 1); let size = 0; while (size < buffer.length) { const { bytesRead } = await file.read(buffer, size, buffer.length - size, null); if (!bytesRead) break; size += bytesRead; } if (size > MAX_BYTES) throw new JevCredentialError("Unsafe credential file"); const value = JSON.parse(buffer.subarray(0, size).toString("utf8")); if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).length !== 1 || !validKey((value as { jev?: unknown }).jev)) throw new JevCredentialError("Invalid credential file"); return (value as { jev: string }).jev; } finally { await file.close(); } }
export type SecretTool = (args: string[], stdin?: string, signal?: AbortSignal) => Promise<string>;
const runSecretTool: SecretTool = (args, stdin, signal) => new Promise((ok, fail) => { const child = execFile("secret-tool", args, { signal, timeout: 30000, killSignal: "SIGKILL", maxBuffer: 16386, encoding: "utf8", shell: false }, (error, stdout) => error ? fail(new JevCredentialError("Linux Secret Service unavailable; no file fallback was used")) : ok(stdout.replace(/\r?\n$/, ""))); child.stdin?.on("error", () => undefined); child.stdin?.end(stdin); });
export async function resolveJevCredential(config: Config, signal?: AbortSignal, env = process.env, secretTool: SecretTool = runSecretTool): Promise<string> { signal?.throwIfAborted(); const { source, reference } = config.jev.credential; if (!validJevReference(source, reference)) throw new JevCredentialError("Invalid credential reference"); if (source === "environment") { const key = env[reference]; if (!validKey(key)) throw new JevCredentialError("Jev credential unavailable"); return key; } if (source === "file") return readFileKey(reference); if (process.platform !== "linux") throw new JevCredentialError("Linux Secret Service unavailable"); const key = await secretTool(["lookup", "application", "pi-guardrails", "service", "jev"], undefined, signal); if (!validKey(key)) throw new JevCredentialError("Jev credential unavailable"); return key; }
export async function saveJevCredential(source: JevCredentialSource, reference: string, key: string, secretTool: SecretTool = runSecretTool): Promise<void> { if (!validJevReference(source, reference) || !validKey(key) || source === "environment") throw new JevCredentialError("Invalid credential settings"); if (source === "keyring") { if (process.platform !== "linux") throw new JevCredentialError("Linux Secret Service unavailable"); await secretTool(["store", "--label=Pi guardrails Jev", "application", "pi-guardrails", "service", "jev"], key); return; } await safePath(reference, true); await mkdir(dirname(reference), { recursive: true, mode: 0o700 }); await safePath(reference, true); try { const existing = await lstat(reference); if (!existing.isFile() || existing.isSymbolicLink()) throw new JevCredentialError("Unsafe credential file"); await readFileKey(reference); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } const temp = `${reference}.${process.pid}.${Date.now()}.tmp`; try { const file = await open(temp, "wx", 0o600); try { await file.writeFile(JSON.stringify({ jev: key }, null, 2) + "\n"); await file.sync(); } finally { await file.close(); } await rename(temp, reference); } finally { await rm(temp, { force: true }).catch(() => undefined); } }
